name: Build and deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      env:
        applicationID: ${{ secrets.APPLICATIONID }}
        searchOnlyAPIKey: ${{ secrets.SEARCHONLYAPIKEY }}
        index_name: ${{ secrets.INDEX_NAME }}

      run: |
        npm install
        npx webpack --mode production --env applicationID=$applicationID --env searchOnlyAPIKey=$searchOnlyAPIKey --env index_name=$index_name
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
